# This is a basic workflow to help you get started with Actions
 
name: deploy vuepress

on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: install node.js
        uses: actions/setup-node@v3.0.0 
        with: 
            node-version: 14

      - name: install yarn
        run: npm install yarn -g

      - name: install pkg
        run: yarn install

      - name: build app
        run: yarn build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          # 本地.ssh文件下的私钥id_rsa，存在secrets的TOKEN中
          SSH_PRIVATE_KEY: ${{ secrets.SSH_TOKEN }} 
          # 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
          ARGS: "-avzr --delete" 
          # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
          SOURCE: "dist" 
          # 服务器域名
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }} 
          # 腾讯云默认用户名为root
          REMOTE_USER: ${{ secrets.REMOTE_NAME }} 
          # 目标目录
          TARGET: ${{ secrets.REMOTE_PATH }} 
          