# This is a basic workflow to help you get started with Actions
 
name: deploy vuepress

on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: install node.js
        uses: actions/setup-node@v3.0.0 
        with: 
            node-version: 14

      - name: install yarn
        run: npm install yarn -g

      - name: install pkg
        run: yarn install

      - name: build app
        run: yarn docs:build
